
# Cross.toml

# Configuration for x86_64 Linux target
[target.x86_64-unknown-linux-gnu]
# Commands to run inside the cross container before building
pre-build = [
    "dpkg --add-architecture arm64 && apt-get update && apt-get install --assume-yes libssl-dev:arm64",
    "apt-get update && apt-get install --assume-yes libssl-dev pkg-config",
]
# You might need to specify a Docker image if the default one doesn't work well
# image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest"

# Configuration for aarch64 Linux target
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev pkg-config",
]
# image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

