[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
CFLAGS_aarch64_unknown_linux_gnu = "-fPIC"
CXXFLAGS_aarch64_unknown_linux_gnu = "-fPIC"
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
CXX_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-g++"
