name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag, or SHA to check out"
        required: true
        type: string
      update-version:
        description: "Update version before building?"
        required: false
        type: boolean
        default: false
      version:
        description: "Version update type (ignored if update-version is false)"
        required: false
        type: string
        default: "patch" # e.g., patch, minor, major, or specific version
      github-release:
        description: "Publish GitHub release?"
        required: false
        type: boolean
        default: false
      tag:
        description: "The release tag (ignored if github-release is false)"
        required: false
        type: string
        default: ""

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          # fetch-depth: 0 # Potentially needed if neon show ci uses git history, uncomment if necessary

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Setup Neon Environment - This uses a local action relative to the repo root.
      # It should NOT have a working-directory set here.
      - name: Setup Neon Environment (Rust/Cross)
        uses: ./.github/actions/setup
        with:
          use-rust: false

      # Run subsequent steps within the package directory
      - name: Install Dependencies
        working-directory: ./markdown-it-gladest
        run: bun install --frozen-lockfile

      - name: Look Up Matrix Data
        id: matrixData
        working-directory: ./markdown-it-gladest
        shell: bash
        run: echo "json=$(bunx neon show ci github | jq -rc)" | tee -a $GITHUB_OUTPUT

      # Compute Matrix doesn't directly interact with files, uses previous step output.
      # No working-directory needed here.
      - name: Compute Matrix
        id: matrix
        uses: actions/github-script@v7
        with:
          script: |
            const platforms = ${{ steps.matrixData.outputs.json }};
            const matrix = [];
            if (platforms.macOS) {
              matrix.push(...platforms.macOS.map(platform => ({ os: "macos-latest", platform, script: "build" })));
            }
            if (platforms.Windows) {
              matrix.push(...platforms.Windows.map(platform => ({ os: "windows-latest", platform, script: "build" })));
            }
            if (platforms.Linux) {
              matrix.push(...platforms.Linux.map(platform => ({ os: "ubuntu-latest", platform, script: "cross" })));
            }
            console.log("Computed Matrix:", matrix);
            return matrix;

  binaries:
    name: Binaries (${{ matrix.cfg.platform }})
    needs: [matrix]
    if: ${{ needs.matrix.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.cfg.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0 # Needed for version bumping

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Setup Neon Environment - Uses local action relative to repo root.
      - name: Setup Neon Environment (Rust/Cross)
        id: neon
        uses: ./.github/actions/setup
        with:
          use-cross: ${{ matrix.cfg.script == 'cross' }}
          platform: ${{ matrix.cfg.platform }}

      # Run subsequent steps within the package directory
      - name: Install Dependencies
        working-directory: ./markdown-it-gladest
        run: bun install --frozen-lockfile

      - name: Update Version
        if: ${{ inputs.update-version }}
        working-directory: ./markdown-it-gladest
        shell: bash
        run: |
          echo "=-=-=-= Debug Info =-=-=-="
          echo "Current directory: $(pwd)"
          echo "Listing node_modules/.bin:"
          ls -l ./node_modules/.bin || echo "node_modules/.bin not found or empty"
          echo "Checking bunx neon --version:"
          bunx neon --version || echo "bunx neon failed"
          echo "Checking bunx neon-cli --version:"
          bunx neon-cli --version || echo "bunx neon-cli failed"
          echo "=-=-=-=-=-=-=-=-=-=-=-=-="

          echo "Running neon bump..."
          bunx neon-cli bump --binaries platforms

          echo "Configuring Git..."
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          bun version ${{ inputs.version }}
          # Git add needs paths relative to the working directory
          echo "Staging changes..."
          git add .
          NEW_VERSION=$(jq -r .version package.json)

          if ! git diff --staged --quiet; then
            NEW_VERSION=$(jq -r .version package.json)
            git commit -m "chore(release): bump version to v${NEW_VERSION}"
            echo "Changes committed."
          else
            echo "No changes to commit."
          fi

      - name: Build Binary
        working-directory: ./markdown-it-gladest
        shell: bash
        env:
          CARGO_BUILD_TARGET: ${{ steps.neon.outputs.target }}
          NEON_BUILD_PLATFORM: ${{ matrix.cfg.platform }}
        run: bun run ${{ matrix.cfg.script }}

      - name: Pack Platform Binary
        id: pack
        # This step involves changing directories *within* the package directory
        working-directory: ./markdown-it-gladest
        shell: bash
        run: |
          # Create dist directory at the REPO ROOT for consistency
          mkdir -p ../dist
          # Change to the platform-specific directory *within* markdown-it-gladest
          cd ./platforms/${{ matrix.cfg.platform }}
          # Pack and output to the REPO ROOT dist directory
          FILENAME=$(bun pack --outdir ../../dist) # Adjust output path relative to current dir
          # No need to cd back, filename is captured
          echo "filename=${FILENAME}" | tee -a $GITHUB_OUTPUT
          echo "Packed file: ../dist/${FILENAME}" # Log the correct path
          ls -l ../dist # List contents of the root dist directory

      # Release Asset step runs at the root level, needs path relative to root
      - name: Release Asset
        if: ${{ inputs.github-release && inputs.tag != '' }}
        uses: softprops/action-gh-release@v2.0.4
        with:
          # Path is relative to the REPO ROOT where the dist dir was created
          files: ./dist/${{ steps.pack.outputs.filename }}
          tag_name: ${{ inputs.tag }}

  main:
    name: Main Package
    needs: [matrix] # Changed from binaries to matrix, as it doesn't depend on binary artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          # If the main package needs the bumped version, you might need fetch-depth: 0
          # and potentially check out *after* the version bump commit is available (complex).
          # Assuming for now it uses the version from the initially checked out ref.

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # No Neon setup needed here based on the original workflow

      # Run subsequent steps within the package directory
      - name: Install Dependencies
        working-directory: ./markdown-it-gladest
        run: bun install --frozen-lockfile

      - name: Pack Main Package
        id: pack
        working-directory: ./markdown-it-gladest
        shell: bash
        run: |
          # Create dist directory at the REPO ROOT
          mkdir -p ../dist
          # Pack and output to the REPO ROOT dist directory
          FILENAME=$(bun pack --outdir ../dist) # Adjust output path relative to working dir
          echo "filename=${FILENAME}" | tee -a $GITHUB_OUTPUT
          echo "Packed file: ../dist/${FILENAME}" # Log the correct path
          ls -l ../dist # List contents of the root dist directory

      # Release Asset step runs at the root level, needs path relative to root
      - name: Release Main Package Asset
        if: ${{ inputs.github-release && inputs.tag != '' }}
        uses: softprops/action-gh-release@v2.0.4
        with:
          # Path is relative to the REPO ROOT where the dist dir was created
          files: ./dist/${{ steps.pack.outputs.filename }}
          tag_name: ${{ inputs.tag }}